### PR TITLE
Rename package

### PR DESCRIPTION
**Pull request by lokshunhung**
#1
﻿

### CODE REVIEW

**Comment by lokshunhung** [comment]
@RageBill
@andyyyu

**Comment by lokshunhung** [comment]
@wongwingho

**Review by wongwingho — CHANGES_REQUESTED** [review]
Looks like there is a typo in the name 
Should use repo name

**Comment by andyyyu** [comment]
Zzz
「James Wong ***@***.***>」在 2021年5月24日週一，下午6:50 寫道：

**Comment by lokshunhung** [comment]
> Looks like there is a typo in the name 
> 
> Should use repo name 

By typo do you mean `jedlander`? I think it should be `jed`. What are your thoughts?

**Pull request merged**
